name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: sudo docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USER }}/deploy-dockerhub .

      - name: Push Image Docker
        run: sudo docker push ${{ secrets.DOCKER_USER }}/deploy-dockerhub

      - name: Docker Pull
        run: sudo docker pull ${{ secrets.DOCKER_USER }}/deploy-dockerhub:latest

      - name: Docker Run
        run: |
    
          sudo docker stop deploy-dockerhub || true
          sudo docker rm deploy-dockerhub || true
          
          sudo docker run -d -p 80:80 -e PORT=${{ secrets.PORT }} --name deploy-dockerhub ${{ secrets.DOCKER_USER }}/deploy-dockerhub