name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Create .env file
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          EOF

      - name: Copy .env to project directory
        run: |
          cp .env /home/ubuntu/deploy-dockerhub/

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/deploy-dockerhub

      - name: Push Image Docker
        run: docker push ${{ secrets.DOCKER_USER }}/deploy-dockerhub

      - name: Docker Pull
        run: docker pull ${{ secrets.DOCKER_USER }}/deploy-dockerhub:latest

      - name: Docker Run
        run: docker run -d -p 80:80 -e PORT=${{ secrets.PORT }} --name deploy-dockerhub:latest ${{ secrets.DOCKER_USER }}/deploy-dockerhub